version: "3.7"

services:
  yacht:
    image: selfhostedpro/yacht
    container_name: yacht
    init: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    networks:
      - proxy
    labels:
      - traefik.http.services.yacht.loadbalancer.server.port=8000
      - traefik.http.routers.yacht.rule=Host(`${FQDN}`)

volumes:
  data: {}

networks:
  proxy:
    external: true
