version: "3.7"

services:
  wordpress:
    image: wordpress
    restart: always
    init: true
    depends_on:
      - mariadb
      - redis
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes_from:
      - wpconfig
    volumes:
      - wordpress:/var/www/html
      #- config/wp-config.php:/var/www/html/wp-config.php
      #- ./upgrade:/var/www/html/wp-content/upgrade
      #- ./plugins:/var/www/html/wp-content/plugins
      #- ./themes:/var/www/html/wp-content/themes
      #- ./uploads:/var/www/html/wp-content/uploads
    env_file:
      - ./stack.env
    networks:
      - proxy
      - internal
    labels:
      traefik.http.services.wordpress.loadbalancer.server.port: 80
      traefik.http.routers.wordpress-https.rule: Host(`${FQDN}`)

  wpconfig:
    image: atareao/wpconfig:v0.1.0

  mariadb:
    image: mariadb
    restart: always
    init: true
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - internal

  backup:
    image: atareao/mariadb-backup:latest
    init: true
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./hooks:/hooks
      - ./backup:/backup
    environment:
      MARIADB_DB: ${DB_NAME}
      MARIADB_HOST: mariadb
      MARIADB_PORT: 3306
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "* * 1/24 * * * *"
      BACKUP_KEEP_MINS: ${BACKUP_KEEP_MINS}
      BACKUP_KEEP_DAYS: ${BACKUP_KEEP_DAYS}
      BACKUP_KEEP_WEEKS: ${BACKUP_KEEP_WEEKS}
      BACKUP_KEEP_MONTHS: ${BACKUP_KEEP_MONTHS}

  redis:
    image: redis:6
    restart: unless-stopped
    init: true
    depends_on:
      - mariadb
    volumes:
      - redis:/data
    networks:
      - internal

volumes:
  wordpress: {}
  db: {}
  redis: {}
  config:
    external: true

networks:
  internal: {}
  proxy:
    external: true
