---
version: "3.7"
services:
  uptime:
    image: louislam/uptime-kuma:1
    init: true
    restart: unless-stopped
    volumes:
      - data
    networks:
      - proxy
    labels:
      - traefik.http.services.uptime.loadbalancer.server.port=3001
      - traefik.http.routers.uptime.rule=Host(`${FQDN}`)
      - internal

volumes:
  data:

networks:
  proxy:
    external: true

